---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "pinot-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: pinot-operator
    app.kubernetes.io/part-of: pinot-operator
    control-plane: controller-manager
  name: {{ include "pinot-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
