# permissions for end users to view pinots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pinot-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pinot-operator
    app.kubernetes.io/part-of: pinot-operator
    app.kubernetes.io/managed-by: kustomize
  name: pinot-viewer-role
rules:
- apiGroups:
  - datainfra.io
  resources:
  - pinots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datainfra.io
  resources:
  - pinots/status
  verbs:
  - get
