# permissions for end users to view pinotschemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pinotschema-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pinot-operator
    app.kubernetes.io/part-of: pinot-operator
    app.kubernetes.io/managed-by: kustomize
  name: pinotschema-viewer-role
rules:
- apiGroups:
  - datainfra.io
  resources:
  - pinotschemas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datainfra.io
  resources:
  - pinotschemas/status
  verbs:
  - get
