# permissions for end users to edit pinottables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pinottable-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pinot-operator
    app.kubernetes.io/part-of: pinot-operator
    app.kubernetes.io/managed-by: kustomize
  name: pinottable-editor-role
rules:
- apiGroups:
  - datainfra.io
  resources:
  - pinottables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - datainfra.io
  resources:
  - pinottables/status
  verbs:
  - get
