# permissions for end users to view pinottenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pinottenant-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pinot-control-plane-k8s
    app.kubernetes.io/part-of: pinot-control-plane-k8s
    app.kubernetes.io/managed-by: kustomize
  name: pinottenant-viewer-role
rules:
- apiGroups:
  - datainfra.io
  resources:
  - pinottenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - datainfra.io
  resources:
  - pinottenants/status
  verbs:
  - get
