---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "pinot-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: pinot-operator
    app.kubernetes.io/part-of: pinot-operator
  name: {{ include "pinot-operator.fullname" . }}-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
